### ISSUE TITLE
modem.mdt not found

### ISSUE THREAD

**Issue by bobobo1618** [sonyxperiadev/device-sony-shinano#150]
Building using the [instructions](developer.sonymobile.com/knowledge-base/open-source/open-devices/aosp-build-instructions/how-to-build-aosp-marshmallow-for-unlocked-xperia-devices/) results in a build that lacks `modem.mdt` as revealed by a ton of `dmesg` messages that looks like so:

```
[    0.000000] cma: Found modem_region@0x8000000, memory base 0x08000000, size 82 MiB, limit 0xffffffff
[    0.000000] cma: CMA: reserved 82 MiB at 0x08000000 for modem_mem
[    0.434041] pil-q6v5-mss fc880000.qcom,mss: [modem]: Error getting proxy unvoting gpio
[    4.860477] usbserial: USB Serial support registered for Qualcomm USB modem
[    9.475994] pil-q6v5-mss fc880000.qcom,mss: modem: Failed to locate modem.mdt
[    9.476007] IPC_RTR: pil_vote_load_worker: Failed to load modem
```

It's unclear where this file originates.

**Comment by humberos** [comment]
@bobobo1618 
I think there is something about proprietary licenses that are blocking those files to distribution.
Anyway you could use SuperBenevolent repos.
https://github.com/SuperBenevolent/
