### ISSUE TITLE
kernel build from source dt_dir error

### ISSUE THREAD

**Issue by rancidfrog** [sonyxperiadev/device-sony-shinano#244]
The following commit states - [https://github.com/sonyxperiadev/device-sony-shinano/commit/f271fcf961526ba4dfa99b248307f4f191366c62]:
```
if vendor/sony/kernel is included in the android tree
we use prebuilt kernel, if folder is not prezent then
kernel is built from source
```
However, 
```
BOARD_MKBOOTIMG_ARGS += --dt_dir $(OUT)/dtbs
```
The above folder is generated by vendor/sony/kernel .
The correct *dt_dir* is **--dt_dir $(OUT)/obj/KERNEL_OBJ/arch/arm/boot/dts**, mentioned by Adam Farden.
vendor/sony/kernel repo should redefine it to: BOARD_MKBOOTIMG_ARGS += --dt_dir $(OUT)/dtbs
As it generates that particular out folder.

**Comment by alviteri** [comment]
you may be informed about inline kernel build... the error in build is related to platform_build on aosp... pick this commit  https://github.com/SonyAosp/platform_build/commit/7db1185a0cb0dfee01024066bc11e11f1c80b6d3and you can close this issue

**Comment by rancidfrog** [comment]
I tried your suggestion, but I get:
```
mkqcdtbootimg: failed to open '.../out/target/product/aries/dtbs': No such file or directory
build/core/Makefile:568: recipe for target '.../out/target/product/aries/boot.img' failed
make: *** [.../out/target/product/aries/boot.img] Error 1
make: *** Waiting for unfinished jobs....
```
The issue lies with creating the boot.img, which relies on **dtbs** folder being present.
However, the folder is generated in vendor/sony/kernel repo which I am not using in custom ROM.
This means that the following commit is not true: https://github.com/sonyxperiadev/device-sony-shinano/commit/f271fcf961526ba4dfa99b248307f4f191366c62
As when vendor/sony/kernel repo is not present, _boot.img creating will always fail_, since **dtbs** folder is missing, as it was not generated (https://github.com/sonyxperiadev/vendor-sony-kernel/blob/master/Android.mk#L14) because vendor-sony-kernel repo is not present.

vendor-sony-kernel should modify **dtbs** folder to BOARD_MKBOOTIMG_ARGS += --dt_dir $(OUT)/dtbs
Otherwise, building boot.img depends on vendor-sony-kernel

**Comment by alviteri** [comment]
Are you building aosp or what?

**Comment by rancidfrog** [comment]
I am building AOSP based custom ROM.

But the issue remains regardless.
Try for yourself building AOSP: remove sony/vendor/kernel repo from manifest and folder
When you build it should build from kernel source. (And not from prebuilt kernel repo)
But, you will get error regarding non-existent folder.
Because the code to generate folder was moved to vendor/sony/kernel: https://github.com/sonyxperiadev/device-sony-shinano/commit/f271fcf961526ba4dfa99b248307f4f191366c62#commitcomment-15707929

**Comment by alviteri** [comment]
are you building M or L ...? if you are building L then that's the problem because that fix I used on M and is working

**Comment by rancidfrog** [comment]
With new appended dtb not needed anymore
