### ISSUE TITLE
in call mics are causing echo on the line

### ISSUE THREAD

**Issue by mcgi5sr2** [sonyxperiadev/device-sony-shinano#349]
The second (top?) mic is receiving the voice sounds from the speaker creating a voice feedback loop that works out like an echo on the line for the second party.

**Comment by rancidfrog** [comment]
@mcgi5sr2 
Have you tried setting `persist.audio.fluence.mode=fluence`, 
In the comments it mentions it but does not set it:
https://github.com/sonyxperiadev/device-sony-common/blob/n-mr1/common.mk#L242
I guess this issue should be in common then,

(You might also need to set `ro.qc.sdk.audio.fluencetype=fluence`)

**Comment by rancidfrog** [comment]
In the following config - https://github.com/sonyxperiadev/device-sony-shinano/blob/n-mr1/rootdir/system/etc/audio_platform_info.xml#L33
 `SND_DEVICE_OUT_VOIP_HANDSET` is set to 7 but `SND_DEVICE_OUT_HANDSET` is not set at all even though it is mentioned below: https://github.com/sonyxperiadev/device-sony-shinano/blob/n-mr1/rootdir/system/etc/audio_platform_info.xml#L44

**Comment by mcgi5sr2** [comment]
Hi @rancidfrog I have a build of AOSP on xda atm that has the stock blobs and fluence commits incorporated.
